### ISSUE TITLE
RemoveLinkTracking doesn't seem to work with Waterfox Classic

### ISSUE THREAD

**Issue by michael-j-oconnor** [Fload2000/RemoveLinkTracking#24]
I disabled all extensions but RemoveLinkTracking with Waterfox Classic 2020.07 (based off FF56) on MacOS.  
I open up Facebook in a new tab.
I don't see fbclid=, utm=, and other tracking URL parameters removed from links provided by friends in Facebook.
What's going wrong, here?  
I'd be glad to load a debug XPI if that helps.

**Comment by f-str** [comment]
I tested it with Waterfox Classic 2020.07 on Linux and couldn't really reproduce it. When I click on links with e.g. utm_ parameters, they get removed.
I couldn't test on MacOS due to I do not own any Apple devices. Maybe I have to set up a VM for that matter, but that could be a little bit tricky and time consuming. 

I wonder if parameters get removed outside of facebook? If this is the case maybe there is some correlation to facebook.

You could try to use the debugger built into the browser to debug the addon.

**Comment by michael-j-oconnor** [comment]
You can close this.  I think the problem I had was MacOS-specific!  I had an NPAPI plugin that was being odd.  I flushed ~/Library/Caches and now RemoveLinkTracking seems to work.  I was looking at the network activity of the browser to determine that it wasn't working before, and is working now.  

It'd be nice if there were a context menu to "Copy Untracked Link" or somesuch, but I think I can chalk this up to odd Mac behavior.  Thanks so much for taking the time to look at this!

**Comment by f-str** [comment]
Thank you for this response. Nice to hear that the issue is resolved and the addon is not the cause.

To have an option on the context menu to copy a cleaned link is actually a pretty cool idea. I'll open a separate feature request for that just keep things organized.
